# Generated by Django 3.2.3 on 2021-07-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
