# Generated by Django 3.2.6 on 2021-08-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_contact_mostrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d'),
        ),
    ]
