# Generated by Django 3.2.7 on 2021-09-02 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0004_contact_foto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categoria',
        ),
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contato',
        ),
    ]
